name: Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  switch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build iptv-player.nro
        run: docker run --platform linux/amd64 --rm -v "$(pwd):/data" devkitpro/devkita64:latest bash /data/scripts/build_switch.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: iptv-player
          path: cmake-build-switch/iptv-player.nro
